spring.application.name=king-tech-backend

# --- CONFIGURATION BASE DE DONNÉES  ---
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.uirxdeqrmmgeloofxpjj
spring.datasource.password=${DB_PASSWORD}
# --- HIBERNATE & JPA ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.type.json_format_mapper=org.hibernate.type.format.jackson.JacksonJsonFormatMapper

# --- CONFIGURATION EMAIL (GMAIL) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sammuel.kouassi2026@gmail.com
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true