spring.application.name=king-tech-backend
# Configuration de la Database
spring.datasource.url=jdbc:postgresql://localhost:5432/kingtech_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# Indique à Hibernate d'utiliser Jackson pour le format JSON
spring.jpa.properties.hibernate.type.json_format_mapper=org.hibernate.type.format.jackson.JacksonJsonFormatMapper
spring.jpa.show-sql=true